### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Baroon-Shrestha** [Baroon-Shrestha/Pets-Nepal#1]
the contents of the footer are incomplete and try to blend the color of the footer to the other contents of the web page.
![Screenshot 2024-04-19 at 20 59 43](https://github.com/Baroon-Shrestha/Pets-Nepal/assets/119175371/a9576139-b8a7-4c10-8be2-fbc0d1ffeecb)

**Comment by Buddha0** [comment]
![image](https://github.com/Baroon-Shrestha/Pets-Nepal/assets/119192602/e02fadf4-aaf7-4649-823a-96c1a176c6ff)
