### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by Baroon-Shrestha** [Baroon-Shrestha/Pets-Nepal#2]
the links of the navigation bar is quite incorrect. I want the favorite link to show only when the user is logged in. also, if the user is admin, the favorite link should not be shown.
<img width="1440" alt="Screenshot 2024-04-19 at 21 01 36" src="https://github.com/Baroon-Shrestha/Pets-Nepal/assets/119175371/41536919-40ad-476b-b19a-eb32404951dc">

**Comment by Baroon-Shrestha** [comment]
fixed

**Comment by Buddha0** [comment]
![Screenshot 2024-04-19 at 21 08 23](https://github.com/Baroon-Shrestha/Pets-Nepal/assets/119192602/8932266f-9798-48a3-a5c0-283396f2906e)
<img width="1440" alt="Screenshot 2024-04-19 at 21 08 42" src="https://github.com/Baroon-Shrestha/Pets-Nepal/assets/119192602/d81192b7-b41e-4c39-9389-f83e6d708475">
